<?php

// One source of truth for the country dropdown, dial codes, ZIP checks,
// phone checks and time zones. Used by RegisterRequest (PHP) and register.js (JavaScript).
//
// ZIP and phone patterns are format checks only. They show the user typed a value in the right
// shape for the country; they do not prove the ZIP or number really exists.
// Phone numbers are typed WITHOUT the leading 0 (the dial code is added separately).

return [
    [
        'name' => 'Argentina',
        'dial' => '+54',
        'zip' => '^[A-Za-z]?\d{4}[A-Za-z]{0,3}$',
        'zip_hint' => 'Enter a postal code like C1024CWN or 1425.',
        'phone' => '^9\d{10}$',
        'phone_hint' => 'Enter 11 digits starting with 9 (example: 91123456789).',
        'timeZone' => 'America/Argentina/Buenos_Aires',
    ],
    [
        'name' => 'Australia',
        'dial' => '+61',
        'zip' => '^\d{4}$',
        'zip_hint' => 'Enter a 4-digit postcode (example: 2000).',
        'phone' => '^4\d{8}$',
        'phone_hint' => 'Enter 9 digits starting with 4 (example: 412345678).',
        'timeZone' => 'Australia/Sydney',
    ],
    [
        'name' => 'Austria',
        'dial' => '+43',
        'zip' => '^\d{4}$',
        'zip_hint' => 'Enter a 4-digit postal code (example: 1010).',
        'phone' => '^6\d{8,11}$',
        'phone_hint' => 'Enter 9 to 12 digits starting with 6 (example: 6641234567).',
        'timeZone' => 'Europe/Vienna',
    ],
    [
        'name' => 'Bangladesh',
        'dial' => '+880',
        'zip' => '^\d{4}$',
        'zip_hint' => 'Enter a 4-digit postal code (example: 1000).',
        'phone' => '^1[3-9]\d{8}$',
        'phone_hint' => 'Enter 10 digits starting with 13 to 19 (example: 1712345678).',
        'timeZone' => 'Asia/Dhaka',
    ],
    [
        'name' => 'Belgium',
        'dial' => '+32',
        'zip' => '^\d{4}$',
        'zip_hint' => 'Enter a 4-digit postal code (example: 1000).',
        'phone' => '^4\d{8}$',
        'phone_hint' => 'Enter 9 digits starting with 4 (example: 470123456).',
        'timeZone' => 'Europe/Brussels',
    ],
    [
        'name' => 'Brazil',
        'dial' => '+55',
        'zip' => '^\d{5}-?\d{3}$',
        'zip_hint' => 'Enter a CEP like 01310-100.',
        'phone' => '^[1-9]{2}9\d{8}$',
        'phone_hint' => 'Enter 11 digits: 2-digit area code, then 9, then 8 digits (example: 11912345678).',
        'timeZone' => 'America/Sao_Paulo',
    ],
    [
        'name' => 'Canada',
        'dial' => '+1',
        'zip' => '^[A-Za-z]\d[A-Za-z][ -]?\d[A-Za-z]\d$',
        'zip_hint' => 'Enter a postal code like K1A 0B1.',
        'phone' => '^[2-9]\d{9}$',
        'phone_hint' => 'Enter 10 digits (example: 6135550123).',
        'timeZone' => 'America/Toronto',
    ],
    [
        'name' => 'Chile',
        'dial' => '+56',
        'zip' => '^\d{7}$',
        'zip_hint' => 'Enter a 7-digit postal code (example: 8320000).',
        'phone' => '^9\d{8}$',
        'phone_hint' => 'Enter 9 digits starting with 9 (example: 912345678).',
        'timeZone' => 'America/Santiago',
    ],
    [
        'name' => 'China',
        'dial' => '+86',
        'zip' => '^\d{6}$',
        'zip_hint' => 'Enter a 6-digit postal code (example: 100000).',
        'phone' => '^1[3-9]\d{9}$',
        'phone_hint' => 'Enter 11 digits starting with 13 to 19 (example: 13812345678).',
        'timeZone' => 'Asia/Shanghai',
    ],
    [
        'name' => 'Colombia',
        'dial' => '+57',
        'zip' => '^\d{6}$',
        'zip_hint' => 'Enter a 6-digit postal code (example: 110111).',
        'phone' => '^3\d{9}$',
        'phone_hint' => 'Enter 10 digits starting with 3 (example: 3123456789).',
        'timeZone' => 'America/Bogota',
    ],
    [
        'name' => 'Denmark',
        'dial' => '+45',
        'zip' => '^\d{4}$',
        'zip_hint' => 'Enter a 4-digit postal code (example: 1050).',
        'phone' => '^[2-9]\d{7}$',
        'phone_hint' => 'Enter 8 digits (example: 20123456).',
        'timeZone' => 'Europe/Copenhagen',
    ],
    [
        'name' => 'Egypt',
        'dial' => '+20',
        'zip' => '^\d{5}$',
        'zip_hint' => 'Enter a 5-digit postal code (example: 11511).',
        'phone' => '^1[0125]\d{8}$',
        'phone_hint' => 'Enter 10 digits starting with 10, 11, 12 or 15 (example: 1012345678).',
        'timeZone' => 'Africa/Cairo',
    ],
    [
        'name' => 'France',
        'dial' => '+33',
        'zip' => '^\d{5}$',
        'zip_hint' => 'Enter a 5-digit postal code (example: 75001).',
        'phone' => '^[67]\d{8}$',
        'phone_hint' => 'Enter 9 digits starting with 6 or 7 (example: 612345678).',
        'timeZone' => 'Europe/Paris',
    ],
    [
        'name' => 'Germany',
        'dial' => '+49',
        'zip' => '^\d{5}$',
        'zip_hint' => 'Enter a 5-digit postal code (example: 10115).',
        'phone' => '^1\d{9,10}$',
        'phone_hint' => 'Enter 10 or 11 digits starting with 1 (example: 15123456789).',
        'timeZone' => 'Europe/Berlin',
    ],
    [
        'name' => 'Greece',
        'dial' => '+30',
        'zip' => '^\d{3}\s?\d{2}$',
        'zip_hint' => 'Enter a postal code like 105 63.',
        'phone' => '^69\d{8}$',
        'phone_hint' => 'Enter 10 digits starting with 69 (example: 6912345678).',
        'timeZone' => 'Europe/Athens',
    ],
    [
        'name' => 'India',
        'dial' => '+91',
        'zip' => '^\d{6}$',
        'zip_hint' => 'Enter a 6-digit PIN code (example: 110001).',
        'phone' => '^[6-9]\d{9}$',
        'phone_hint' => 'Enter 10 digits starting with 6, 7, 8 or 9 (example: 9876543210).',
        'timeZone' => 'Asia/Kolkata',
    ],
    [
        'name' => 'Indonesia',
        'dial' => '+62',
        'zip' => '^\d{5}$',
        'zip_hint' => 'Enter a 5-digit postal code (example: 10110).',
        'phone' => '^8\d{8,11}$',
        'phone_hint' => 'Enter 9 to 12 digits starting with 8 (example: 812345678).',
        'timeZone' => 'Asia/Jakarta',
    ],
    [
        'name' => 'Ireland',
        'dial' => '+353',
        'zip' => '^[A-Za-z]\d[\dWw]\s?[A-Za-z\d]{4}$',
        'zip_hint' => 'Enter an Eircode like D02 X285.',
        'phone' => '^8\d{8}$',
        'phone_hint' => 'Enter 9 digits starting with 8 (example: 851234567).',
        'timeZone' => 'Europe/Dublin',
    ],
    [
        'name' => 'Israel',
        'dial' => '+972',
        'zip' => '^\d{7}$',
        'zip_hint' => 'Enter a 7-digit postal code (example: 9103001).',
        'phone' => '^5\d{8}$',
        'phone_hint' => 'Enter 9 digits starting with 5 (example: 521234567).',
        'timeZone' => 'Asia/Jerusalem',
    ],
    [
        'name' => 'Italy',
        'dial' => '+39',
        'zip' => '^\d{5}$',
        'zip_hint' => 'Enter a 5-digit postal code (example: 00184).',
        'phone' => '^3\d{8,9}$',
        'phone_hint' => 'Enter 9 or 10 digits starting with 3 (example: 3123456789).',
        'timeZone' => 'Europe/Rome',
    ],
    [
        'name' => 'Japan',
        'dial' => '+81',
        'zip' => '^\d{3}-?\d{4}$',
        'zip_hint' => 'Enter a postal code like 100-0001.',
        'phone' => '^[789]0\d{8}$',
        'phone_hint' => 'Enter 10 digits starting with 70, 80 or 90 (example: 9012345678).',
        'timeZone' => 'Asia/Tokyo',
    ],
    [
        'name' => 'Kenya',
        'dial' => '+254',
        'zip' => '^\d{5}$',
        'zip_hint' => 'Enter a 5-digit postal code (example: 00100).',
        'phone' => '^[17]\d{8}$',
        'phone_hint' => 'Enter 9 digits starting with 1 or 7 (example: 712345678).',
        'timeZone' => 'Africa/Nairobi',
    ],
    [
        'name' => 'Malaysia',
        'dial' => '+60',
        'zip' => '^\d{5}$',
        'zip_hint' => 'Enter a 5-digit postcode (example: 50450).',
        'phone' => '^1\d{8,9}$',
        'phone_hint' => 'Enter 9 or 10 digits starting with 1 (example: 123456789).',
        'timeZone' => 'Asia/Kuala_Lumpur',
    ],
    [
        'name' => 'Mexico',
        'dial' => '+52',
        'zip' => '^\d{5}$',
        'zip_hint' => 'Enter a 5-digit postal code (example: 06600).',
        'phone' => '^[1-9]\d{9}$',
        'phone_hint' => 'Enter 10 digits (example: 5512345678).',
        'timeZone' => 'America/Mexico_City',
    ],
    [
        'name' => 'Netherlands',
        'dial' => '+31',
        'zip' => '^\d{4}\s?[A-Za-z]{2}$',
        'zip_hint' => 'Enter a postal code like 1012 AB.',
        'phone' => '^6\d{8}$',
        'phone_hint' => 'Enter 9 digits starting with 6 (example: 612345678).',
        'timeZone' => 'Europe/Amsterdam',
    ],
    [
        'name' => 'New Zealand',
        'dial' => '+64',
        'zip' => '^\d{4}$',
        'zip_hint' => 'Enter a 4-digit postcode (example: 6011).',
        'phone' => '^2\d{7,9}$',
        'phone_hint' => 'Enter 8 to 10 digits starting with 2 (example: 211234567).',
        'timeZone' => 'Pacific/Auckland',
    ],
    [
        'name' => 'Nigeria',
        'dial' => '+234',
        'zip' => '^\d{6}$',
        'zip_hint' => 'Enter a 6-digit postal code (example: 100001).',
        'phone' => '^[789]\d{9}$',
        'phone_hint' => 'Enter 10 digits starting with 7, 8 or 9 (example: 8012345678).',
        'timeZone' => 'Africa/Lagos',
    ],
    [
        'name' => 'Norway',
        'dial' => '+47',
        'zip' => '^\d{4}$',
        'zip_hint' => 'Enter a 4-digit postal code (example: 0150).',
        'phone' => '^[49]\d{7}$',
        'phone_hint' => 'Enter 8 digits starting with 4 or 9 (example: 41234567).',
        'timeZone' => 'Europe/Oslo',
    ],
    [
        'name' => 'Pakistan',
        'dial' => '+92',
        'zip' => '^\d{5}$',
        'zip_hint' => 'Enter a 5-digit postal code (example: 44000).',
        'phone' => '^3\d{9}$',
        'phone_hint' => 'Enter 10 digits starting with 3 (example: 3012345678).',
        'timeZone' => 'Asia/Karachi',
    ],
    [
        'name' => 'Philippines',
        'dial' => '+63',
        'zip' => '^\d{4}$',
        'zip_hint' => 'Enter a 4-digit ZIP code (example: 1100).',
        'phone' => '^9\d{9}$',
        'phone_hint' => 'Enter 10 digits starting with 9, without the leading 0 (example: 9171234567).',
        'timeZone' => 'Asia/Manila',
    ],
    [
        'name' => 'Poland',
        'dial' => '+48',
        'zip' => '^\d{2}-\d{3}$',
        'zip_hint' => 'Enter a postal code like 00-950.',
        'phone' => '^[4-8]\d{8}$',
        'phone_hint' => 'Enter 9 digits starting with 4 to 8 (example: 512345678).',
        'timeZone' => 'Europe/Warsaw',
    ],
    [
        'name' => 'Portugal',
        'dial' => '+351',
        'zip' => '^\d{4}-?\d{3}$',
        'zip_hint' => 'Enter a postal code like 1000-001.',
        'phone' => '^9\d{8}$',
        'phone_hint' => 'Enter 9 digits starting with 9 (example: 912345678).',
        'timeZone' => 'Europe/Lisbon',
    ],
    [
        'name' => 'Saudi Arabia',
        'dial' => '+966',
        'zip' => '^\d{5}$',
        'zip_hint' => 'Enter a 5-digit postal code (example: 11564).',
        'phone' => '^5\d{8}$',
        'phone_hint' => 'Enter 9 digits starting with 5 (example: 512345678).',
        'timeZone' => 'Asia/Riyadh',
    ],
    [
        'name' => 'South Africa',
        'dial' => '+27',
        'zip' => '^\d{4}$',
        'zip_hint' => 'Enter a 4-digit postal code (example: 0001).',
        'phone' => '^[678]\d{8}$',
        'phone_hint' => 'Enter 9 digits starting with 6, 7 or 8 (example: 821234567).',
        'timeZone' => 'Africa/Johannesburg',
    ],
    [
        'name' => 'South Korea',
        'dial' => '+82',
        'zip' => '^\d{5}$',
        'zip_hint' => 'Enter a 5-digit postal code (example: 04524).',
        'phone' => '^1\d{8,9}$',
        'phone_hint' => 'Enter 9 or 10 digits starting with 1 (example: 1012345678).',
        'timeZone' => 'Asia/Seoul',
    ],
    [
        'name' => 'Spain',
        'dial' => '+34',
        'zip' => '^\d{5}$',
        'zip_hint' => 'Enter a 5-digit postal code (example: 28013).',
        'phone' => '^[67]\d{8}$',
        'phone_hint' => 'Enter 9 digits starting with 6 or 7 (example: 612345678).',
        'timeZone' => 'Europe/Madrid',
    ],
    [
        'name' => 'Sri Lanka',
        'dial' => '+94',
        'zip' => '^\d{5}$',
        'zip_hint' => 'Enter a 5-digit postal code (example: 00100).',
        'phone' => '^7\d{8}$',
        'phone_hint' => 'Enter 9 digits starting with 7 (example: 712345678).',
        'timeZone' => 'Asia/Colombo',
    ],
    [
        'name' => 'Sweden',
        'dial' => '+46',
        'zip' => '^\d{3}\s?\d{2}$',
        'zip_hint' => 'Enter a postal code like 111 22.',
        'phone' => '^7\d{8}$',
        'phone_hint' => 'Enter 9 digits starting with 7 (example: 701234567).',
        'timeZone' => 'Europe/Stockholm',
    ],
    [
        'name' => 'Switzerland',
        'dial' => '+41',
        'zip' => '^\d{4}$',
        'zip_hint' => 'Enter a 4-digit postal code (example: 8001).',
        'phone' => '^7[5-9]\d{7}$',
        'phone_hint' => 'Enter 9 digits starting with 75 to 79 (example: 791234567).',
        'timeZone' => 'Europe/Zurich',
    ],
    [
        'name' => 'Thailand',
        'dial' => '+66',
        'zip' => '^\d{5}$',
        'zip_hint' => 'Enter a 5-digit postal code (example: 10110).',
        'phone' => '^[689]\d{8}$',
        'phone_hint' => 'Enter 9 digits starting with 6, 8 or 9 (example: 812345678).',
        'timeZone' => 'Asia/Bangkok',
    ],
    [
        'name' => 'Turkey',
        'dial' => '+90',
        'zip' => '^\d{5}$',
        'zip_hint' => 'Enter a 5-digit postal code (example: 34000).',
        'phone' => '^5\d{9}$',
        'phone_hint' => 'Enter 10 digits starting with 5 (example: 5321234567).',
        'timeZone' => 'Europe/Istanbul',
    ],
    [
        'name' => 'United Kingdom',
        'dial' => '+44',
        'zip' => '^[A-Za-z]{1,2}\d[A-Za-z\d]?\s?\d[A-Za-z]{2}$',
        'zip_hint' => 'Enter a postcode like SW1A 1AA.',
        'phone' => '^7\d{9}$',
        'phone_hint' => 'Enter 10 digits starting with 7 (example: 7400123456).',
        'timeZone' => 'Europe/London',
    ],
    [
        'name' => 'United States',
        'dial' => '+1',
        'zip' => '^\d{5}(-\d{4})?$',
        'zip_hint' => 'Enter a ZIP code like 90210 or 90210-1234.',
        'phone' => '^[2-9]\d{9}$',
        'phone_hint' => 'Enter 10 digits (example: 2125551234).',
        'timeZone' => 'America/New_York',
    ],
    [
        'name' => 'Vietnam',
        'dial' => '+84',
        'zip' => '^\d{6}$',
        'zip_hint' => 'Enter a 6-digit postal code (example: 100000).',
        'phone' => '^[35789]\d{8}$',
        'phone_hint' => 'Enter 9 digits starting with 3, 5, 7, 8 or 9 (example: 912345678).',
        'timeZone' => 'Asia/Ho_Chi_Minh',
    ],
];