<?php

// One source of truth for the country dropdown, dial codes, ZIP checks,
// phone checks and time zones. Used by RegisterRequest (PHP) and register.js (JavaScript).
// The first entry is the default selection.

return [
    [
        'name' => 'Philippines',
        'dial' => '+63',
        'zip' => '^\d{4}$',
        'zip_hint' => 'Enter a 4-digit ZIP code (example: 1100).',
        'phone' => '^9\d{9}$',
        'phone_hint' => 'Enter 10 digits starting with 9, without the leading 0 (example: 9171234567).',
        'timeZone' => 'Asia/Manila',
    ],
    [
        'name' => 'United States',
        'dial' => '+1',
        'zip' => '^\d{5}(-\d{4})?$',
        'zip_hint' => 'Enter a ZIP code like 90210 or 90210-1234.',
        'phone' => '^[2-9]\d{9}$',
        'phone_hint' => 'Enter 10 digits (example: 2125551234).',
        'timeZone' => 'America/New_York',
    ],
    [
        'name' => 'Canada',
        'dial' => '+1',
        'zip' => '^[A-Za-z]\d[A-Za-z][ -]?\d[A-Za-z]\d$',
        'zip_hint' => 'Enter a postal code like K1A 0B1.',
        'phone' => '^[2-9]\d{9}$',
        'phone_hint' => 'Enter 10 digits (example: 6135550123).',
        'timeZone' => 'America/Toronto',
    ],
    [
        'name' => 'United Kingdom',
        'dial' => '+44',
        'zip' => '^[A-Za-z]{1,2}\d[A-Za-z\d]?\s?\d[A-Za-z]{2}$',
        'zip_hint' => 'Enter a postcode like SW1A 1AA.',
        'phone' => '^7\d{9}$',
        'phone_hint' => 'Enter 10 digits starting with 7 (example: 7400123456).',
        'timeZone' => 'Europe/London',
    ],
    [
        'name' => 'Australia',
        'dial' => '+61',
        'zip' => '^\d{4}$',
        'zip_hint' => 'Enter a 4-digit postcode (example: 2000).',
        'phone' => '^4\d{8}$',
        'phone_hint' => 'Enter 9 digits starting with 4 (example: 412345678).',
        'timeZone' => 'Australia/Sydney',
    ],
    [
        'name' => 'Singapore',
        'dial' => '+65',
        'zip' => '^\d{6}$',
        'zip_hint' => 'Enter a 6-digit postal code (example: 018956).',
        'phone' => '^[89]\d{7}$',
        'phone_hint' => 'Enter 8 digits starting with 8 or 9 (example: 81234567).',
        'timeZone' => 'Asia/Singapore',
    ],
    [
        'name' => 'Japan',
        'dial' => '+81',
        'zip' => '^\d{3}-?\d{4}$',
        'zip_hint' => 'Enter a postal code like 100-0001.',
        'phone' => '^[789]0\d{8}$',
        'phone_hint' => 'Enter 10 digits starting with 70, 80 or 90 (example: 9012345678).',
        'timeZone' => 'Asia/Tokyo',
    ],
    [
        'name' => 'South Korea',
        'dial' => '+82',
        'zip' => '^\d{5}$',
        'zip_hint' => 'Enter a 5-digit postal code (example: 04524).',
        'phone' => '^1\d{8,9}$',
        'phone_hint' => 'Enter 9 or 10 digits starting with 1 (example: 1012345678).',
        'timeZone' => 'Asia/Seoul',
    ],
    [
        'name' => 'India',
        'dial' => '+91',
        'zip' => '^\d{6}$',
        'zip_hint' => 'Enter a 6-digit PIN code (example: 110001).',
        'phone' => '^[6-9]\d{9}$',
        'phone_hint' => 'Enter 10 digits starting with 6, 7, 8 or 9 (example: 9876543210).',
        'timeZone' => 'Asia/Kolkata',
    ],
    [
        'name' => 'Malaysia',
        'dial' => '+60',
        'zip' => '^\d{5}$',
        'zip_hint' => 'Enter a 5-digit postcode (example: 50450).',
        'phone' => '^1\d{8,9}$',
        'phone_hint' => 'Enter 9 or 10 digits starting with 1 (example: 123456789).',
        'timeZone' => 'Asia/Kuala_Lumpur',
    ],
    [
        'name' => 'Indonesia',
        'dial' => '+62',
        'zip' => '^\d{5}$',
        'zip_hint' => 'Enter a 5-digit postal code (example: 10110).',
        'phone' => '^8\d{8,11}$',
        'phone_hint' => 'Enter 9 to 12 digits starting with 8 (example: 812345678).',
        'timeZone' => 'Asia/Jakarta',
    ],
    [
        'name' => 'Germany',
        'dial' => '+49',
        'zip' => '^\d{5}$',
        'zip_hint' => 'Enter a 5-digit postal code (example: 10115).',
        'phone' => '^1\d{9,10}$',
        'phone_hint' => 'Enter 10 or 11 digits starting with 1 (example: 15123456789).',
        'timeZone' => 'Europe/Berlin',
    ],
    [
        'name' => 'France',
        'dial' => '+33',
        'zip' => '^\d{5}$',
        'zip_hint' => 'Enter a 5-digit postal code (example: 75001).',
        'phone' => '^[67]\d{8}$',
        'phone_hint' => 'Enter 9 digits starting with 6 or 7 (example: 612345678).',
        'timeZone' => 'Europe/Paris',
    ],
];